[project]
name = "ai-basic-alina"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"accelerate",
	"diffusers",
	"numpy",
	"opencv-python",
	"pillow",
	"safetensors",
	"scikit-image>=0.26.0",
	"torch",
	"torchvision>=0.28.0",
	"transformers",
]
