"""Оркестрация прогонов ``run`` / ``regenerate``.

Модуль НЕ импортирует ``engines`` на верхнем уровне и ничего не знает про
torch: работает только через :class:`datasetgen.engines.Dependencies`,
переданный вызывающим кодом (в тестах — фейки).
"""

from __future__ import annotations

import hashlib
import time
from collections.abc import Callable, Mapping, Sequence
from contextlib import ExitStack
from datetime import timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from . import layout
from .bootstrap import ensure_legacy_importable
from .description import write_reports
from .errors import EXIT_GENERATION_FAILED, EXIT_OK, ConfigError, UnsafePathError
from .manifest import SCHEMA_VERSION, Manifest, ManifestState
from .paths import validate_output_dir
from .planner import (
    all_keys,
    background_prompt,
    build_plan,
    cutter_model_name,
    inpaint_seed,
    settings_for,
)
from .schema import (
    MODE_TWO,
    STATUS_FAILED,
    STATUS_PLANNED,
    STATUS_REJECTED,
    STATUS_SUCCEEDED,
    JobConfig,
    Plan,
    PlannedOutput,
    RunResult,
)

if TYPE_CHECKING:  # pragma: no cover - только для аннотаций
    from .engines import Dependencies

STAGE_GUARD = "guard"
STAGE_SUBJECT = "subject"
STAGE_CUT = "cut"
STAGE_INPAINT = "inpaint"
STAGE_SINGLE = "single"
STAGE_SAVE = "save"

#: Сентинел «параметр не передан» (в отличие от ``None`` — «передан как None»).
_UNSET = object()


class _GuardViolation(Exception):
    """Попытка воспроизвести уже существующую реализацию (seed, prompt)."""

    def __init__(self, message: str) -> None:
        super().__init__(message)
        self.message = message


class _NullWriter:
    def write(self, text: str) -> int:  # pragma: no cover - тривиально
        return len(text)


class _Execution:
    """Один прогон: подготовка, план, запись манифеста, вызовы legacy-обёрток."""

    def __init__(
        self,
        job: JobConfig,
        model_id: str,
        output_dir: Path | None,
        dry_run: bool,
        deps: "Dependencies",
        command: str,
        *,
        out: Any,
        warn: Callable[[str], None],
        error: Callable[[str], None],
    ) -> None:
        self.job = job
        self.model_id = model_id
        self.requested_output = Path(output_dir) if output_dir is not None else job.output_dir
        self.dry_run = dry_run
        self.deps = deps
        self.command = command
        self.out = out
        self.warn = warn
        self.error = error
        self.root: Path | None = None
        self.manifest: Manifest | None = None
        self.state: ManifestState = ManifestState()
        self.run_id = ""
        self.started_at = ""
        self.rejected_moved = 0
        self.failures: list[str] = []

    # ----------------------------------------------------------------- утилиты
    def _print(self, message: str = "") -> None:
        self.out.write(message + "\n")

    def _timestamp(self) -> str:
        moment = self.deps.clock()
        if getattr(moment, "tzinfo", None) is None:
            moment = moment.replace(tzinfo=timezone.utc)
        return moment.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    def _make_run_id(self, started_at: str) -> str:
        digest = hashlib.sha256(
            "|".join([self.job.raw_sha256, self.model_id, started_at, self.command]).encode("utf-8")
        ).hexdigest()[:8]
        return f"{started_at.replace('-', '').replace(':', '')}-{digest}"

    # --------------------------------------------------------------- подготовка
    def _prepare(self, selection: Sequence[tuple[str, int]] | None = None) -> Plan:
        self.root = validate_output_dir(self.requested_output, self.job.source_path)
        manifest = Manifest.load(layout.manifest_path(self.root), warn=self.warn)
        self.manifest = manifest
        self._check_manifest_identity(manifest)
        self.state = manifest.state()
        if selection is None:
            skip = [key for key in all_keys(self.job) if self.state.is_rejected(key)]
            if skip:
                self.warn(
                    f"{len(skip)} rejected output(s) are not regenerated by 'run' "
                    "(use 'regenerate --remove ...')"
                )
            return build_plan(
                self.job,
                self.model_id,
                self.command,
                max_attempts=self.state.max_attempt,
                complete_flags=self._complete_flags(),
                skip=skip,
                planned_attempts=self._resume_attempts(),
            )
        return build_plan(
            self.job,
            self.model_id,
            self.command,
            max_attempts=self.state.max_attempt,
            selection=selection,
        )

    def _check_manifest_identity(self, manifest: Manifest) -> None:
        last_run = manifest.last_run_record()
        if last_run is None:
            return
        recorded = str(last_run.get("output_dir", ""))
        if recorded and recorded != str(self.root):
            raise UnsafePathError(
                f"output_dir differs from the manifest record: {recorded} (refusing to mix datasets)"
            )
        previous_digest = last_run.get("job_sha256")
        if previous_digest and previous_digest != self.job.raw_sha256:
            self.warn(
                "job file changed since the last run "
                f"({str(previous_digest)[:12]} -> {self.job.raw_sha256[:12]})"
            )

    def _resume_attempts(self) -> dict[tuple[str, int], int]:
        """Незавершённая ``planned``-попытка продолжается с тем же номером.

        Иначе (нет записей / ``failed`` / ``rejected`` / ``succeeded`` без файла)
        номер увеличивается на 1 — это новая работа.
        """

        attempts: dict[tuple[str, int], int] = {}
        for key in all_keys(self.job):
            last = self.state.last_record(key)
            if last is not None and last.get("status") == STATUS_PLANNED:
                attempts[key] = int(last.get("attempt", 1))
        return attempts

    def _complete_flags(self) -> dict[tuple[str, int], bool]:
        flags: dict[tuple[str, int], bool] = {}
        for class_name, index in all_keys(self.job):
            if not self.state.has_succeeded((class_name, index)):
                flags[(class_name, index)] = False
                continue
            path = layout.final_image_path(self.root, class_name, index)
            flags[(class_name, index)] = path.is_file() and path.stat().st_size > 0
        return flags

    def _preflight_overwrite(self, plan: Plan) -> None:
        """R5: чужой файл не перезаписываем."""

        for planned in plan.outputs:
            final = layout.final_image_path(self.root, planned.class_name, planned.index)
            if not final.exists():
                continue
            if self.state.has_succeeded(planned.key):
                continue
            # Остаток упавшей или прерванной попытки — тоже наш файл: на него
            # ссылается хотя бы одна image-запись, поэтому R5 соблюдён и батч
            # не валится из-за недописанного предыдущего кадра.
            if self.state.owns_output(planned.key, layout.relative_posix(self.root, final)):
                continue
            raise UnsafePathError(
                f"refusing to overwrite unmanaged file: {final} "
                "(no matching manifest record; move it aside or choose another --output-dir)"
            )

    def _make_directories(self) -> None:
        """F-4: каталоги создаются ДО любой работы со сканером каталогов."""

        self.root.mkdir(parents=True, exist_ok=True)
        for spec in self.job.classes:
            layout.class_dir(self.root, spec.name).mkdir(parents=True, exist_ok=True)
        if self.job.generation.mode == MODE_TWO:
            for spec in self.job.classes:
                layout.intermediate_dir(self.root, spec.name).mkdir(parents=True, exist_ok=True)

    def _disk_gap_report(self) -> None:
        """Read-only сверка нумерации на диске через legacy ``filesystems_core``."""

        ensure_legacy_importable()
        from filesystems_core import ComradeManager  # noqa: PLC0415 - legacy-делегат

        for spec in self.job.classes:
            directory = layout.class_dir(self.root, spec.name)
            if not directory.is_dir():
                continue
            gaps = ComradeManager(directory, prefix=spec.name).find_missing_numbers()
            if gaps:
                self.warn(
                    f"{spec.name}/ has numbering gaps on disk: "
                    + ", ".join(str(number) for number in gaps)
                )

    # --------------------------------------------------------------- манифест
    def _two_layer_block(self) -> dict | None:
        background = self.job.generation.background
        if background is None:
            return None
        return {
            "background_model_id": background.model_id,
            "cutter": self.job.generation.cutter,
            "background_prompt": background.prompt.template,
            "background_inference": settings_for(background.inference),
        }

    def _write_run_record(self, removed: Sequence[tuple[str, int]] | None = None) -> None:
        record = {
            "schema_version": SCHEMA_VERSION,
            "type": "run",
            "run_id": self.run_id,
            "command": self.command,
            "started_at": self.started_at,
            "job_file": str(self.job.source_path),
            "job_sha256": self.job.raw_sha256,
            "output_dir": str(self.root),
            "task": self.job.task,
            "generation_mode": self.job.generation.mode,
            "model_id": self.model_id,
            "job_seed": self.job.seed,
            "classes": [{"name": spec.name, "count": spec.count} for spec in self.job.classes],
            "inference": settings_for(self.job.inference),
            "two_layer": self._two_layer_block(),
        }
        if removed is not None:
            record["removed"] = [{"class": name, "index": index} for name, index in removed]
        self.manifest.append(record)

    def _image_record(
        self,
        planned: PlannedOutput,
        status: str,
        *,
        timestamp: str,
        intermediates: Sequence[Path] = (),
        attempt: int | None = None,
        error: Mapping | None = None,
        size: int | None = None,
        duration: float | None = None,
        rejected_file: Any = _UNSET,
        reason: Any = _UNSET,
        seed: Any = "__unset__",
        prompt: Any = "__unset__",
        negative_prompt: Any = "__unset__",
    ) -> dict:
        def pick(value: Any, fallback: Any) -> Any:
            return fallback if value == "__unset__" else value

        record = {
            "schema_version": SCHEMA_VERSION,
            "type": "image",
            "run_id": self.run_id,
            "class": planned.class_name,
            "index": planned.index,
            "attempt": planned.attempt if attempt is None else attempt,
            "status": status,
            "output": layout.relative_posix(
                self.root, layout.final_image_path(self.root, planned.class_name, planned.index)
            ),
            "prompt": pick(prompt, planned.prompt),
            "negative_prompt": pick(negative_prompt, planned.negative_prompt),
            "seed": pick(seed, planned.seed),
            "model_id": self.model_id,
            "settings": dict(planned.settings),
            "generation_mode": self.job.generation.mode,
            "intermediate": [layout.relative_posix(self.root, path) for path in intermediates],
            "timestamp": timestamp,
            "error": dict(error) if error else None,
            "bytes": size,
            "duration_sec": duration,
        }
        if rejected_file is not _UNSET:
            # rejected-запись ВСЕГДА свидетельствует, что именно отклонено, даже
            # если переносить было нечего (тогда rejected_file === null).
            record["rejected_file"] = rejected_file
            record["rejected_at"] = timestamp
            record["reason"] = "cli --remove" if reason is _UNSET or reason is None else reason
        return record

    # ------------------------------------------------------------------ guard
    def _guard_message(self, planned: PlannedOutput) -> str | None:
        """Инвариант: новая попытка не повторяет НИ ОДНУ прошлую реализацию.

        Сверяемся со всеми ``planned``/``succeeded``/``rejected``-записями ключа,
        а не только с последней, чтобы инвариант «никогда не воспроизводим
        отклонённое» был исполнимым, а не вероятностным.
        """

        duplicated = any(
            previous.get("seed") == planned.seed and previous.get("prompt") == planned.prompt
            for previous in self.state.realizations(planned.key)
        )
        if not duplicated:
            return None
        spec = self.job.class_spec(planned.class_name)
        singletons = [
            name for name in sorted(spec.prompt.variables) if len(spec.prompt.variables[name]) == 1
        ]
        names = singletons or sorted(spec.prompt.variables)
        return (
            "refusing to reproduce an identical (seed, prompt) realization for "
            f"{planned.class_name} index {planned.index} attempt {planned.attempt}: "
            f"add more alternatives to variables [{', '.join(names)}]"
        )

    # ------------------------------------------------------------- генерация
    def _intermediates(self, planned: PlannedOutput) -> tuple[Path, ...]:
        if self.job.generation.mode != MODE_TWO:
            return ()
        return (
            layout.intermediate_path(
                self.root, planned.class_name, planned.index, planned.attempt, "subject"
            ),
            layout.intermediate_path(
                self.root, planned.class_name, planned.index, planned.attempt, "cut"
            ),
        )

    def _single_generator(
        self, planned: PlannedOutput, provider: Callable[[], Any]
    ) -> Callable[[dict], None]:
        final = layout.final_image_path(self.root, planned.class_name, planned.index)

        def generate(context: dict) -> None:
            context["stage"] = STAGE_SINGLE
            prompts = self.deps.legacy_types.prompts(planned.prompt, planned.negative_prompt)
            config = self.deps.legacy_types.params(planned.seed, self.job.inference)
            provider().generate_image(prompts=prompts, config=config, save_path=final)

        return generate

    def _two_layer_generator(self, planned: PlannedOutput) -> Callable[[dict], None]:
        root = self.root
        job = self.job
        background = job.generation.background
        final = layout.final_image_path(root, planned.class_name, planned.index)
        subject = layout.intermediate_path(
            root, planned.class_name, planned.index, planned.attempt, "subject"
        )
        cut = layout.intermediate_path(
            root, planned.class_name, planned.index, planned.attempt, "cut"
        )

        def generate(context: dict) -> None:
            from PIL import Image  # noqa: PLC0415 - ленивый импорт по F-5

            context["stage"] = STAGE_SUBJECT
            prompts = self.deps.legacy_types.prompts(planned.prompt, planned.negative_prompt)
            config = self.deps.legacy_types.params(planned.seed, job.inference)
            with self.deps.backends.make_generator(self.model_id) as generator:
                generator.generate_image(prompts=prompts, config=config, save_path=subject)
            context["stage"] = STAGE_SAVE
            self._assert_written(subject)
            context["stage"] = STAGE_CUT
            with self.deps.backends.make_cutter(cutter_model_name(job.generation)) as cutter:
                with Image.open(subject) as source:
                    cutter.remove_background(image=source, save_path=cut)
            context["stage"] = STAGE_SAVE
            self._assert_written(cut)
            context["stage"] = STAGE_INPAINT
            background_prompts = self.deps.legacy_types.prompts(
                background_prompt(job, planned.material), background.prompt.negative_prompt
            )
            background_config = self.deps.legacy_types.params(
                inpaint_seed(planned.material), background.inference
            )
            with self.deps.backends.make_inpainter(background.model_id) as inpainter:
                with Image.open(subject) as source, Image.open(cut) as mask:
                    inpainter.inpaint_image(
                        prompts=background_prompts,
                        config=background_config,
                        image=source,
                        mask=mask,
                        save_path=final,
                    )
            context["stage"] = STAGE_SAVE
            self._assert_written(final)

        return generate

    def _assert_written(self, path: Path) -> None:
        if not path.is_file() or path.stat().st_size <= 0:
            raise RuntimeError(f"backend did not produce a non-empty file: {path}")

    def _process_output(
        self,
        planned: PlannedOutput,
        generate: Callable[[dict], None],
        intermediates: Sequence[Path],
        *,
        guard_violation: str | None = None,
    ) -> bool:
        """Один выход: planned -> (succeeded | failed). Исключение наружу не выходит."""

        context = {"stage": STAGE_GUARD}
        self.manifest.append(
            self._image_record(
                planned, STATUS_PLANNED, timestamp=self._timestamp(), intermediates=intermediates
            )
        )
        started = time.perf_counter()
        try:
            if guard_violation is not None:
                raise _GuardViolation(guard_violation)
            generate(context)
            context["stage"] = STAGE_SAVE
            self._assert_written(
                layout.final_image_path(self.root, planned.class_name, planned.index)
            )
        except _GuardViolation as violation:
            duration = round(time.perf_counter() - started, 2)
            self.manifest.append(
                self._image_record(
                    planned,
                    STATUS_FAILED,
                    timestamp=self._timestamp(),
                    error={
                        "type": ConfigError.code,
                        "message": violation.message,
                        "stage": STAGE_GUARD,
                    },
                    duration=duration,
                )
            )
            self.error(f"datasetgen: error: [{ConfigError.code}] {violation.message}")
            self.failures.append(violation.message)
            self._print(
                f"  {planned.class_name}/{planned.index} attempt={planned.attempt}"
                f" -> failed ({STAGE_GUARD})"
            )
            return False
        except Exception as exc:  # noqa: BLE001 - политика одной ошибки
            duration = round(time.perf_counter() - started, 2)
            message = str(exc) or type(exc).__name__
            self.manifest.append(
                self._image_record(
                    planned,
                    STATUS_FAILED,
                    timestamp=self._timestamp(),
                    error={"type": type(exc).__name__, "message": message, "stage": context["stage"]},
                    duration=duration,
                )
            )
            self.failures.append(f"{planned.class_name}/{planned.index}: {message}")
            self._print(
                f"  {planned.class_name}/{planned.index} attempt={planned.attempt}"
                f" -> failed ({context['stage']}): {message}"
            )
            return False
        final = layout.final_image_path(self.root, planned.class_name, planned.index)
        duration = round(time.perf_counter() - started, 2)
        self.manifest.append(
            self._image_record(
                planned,
                STATUS_SUCCEEDED,
                timestamp=self._timestamp(),
                intermediates=intermediates,
                size=final.stat().st_size,
                duration=duration,
            )
        )
        return True

    # -------------------------------------------------------------- цикл выходов
    def _generator_for(
        self, planned: PlannedOutput, provider: Callable[[], Any] | None
    ) -> Callable[[dict], None]:
        if self.job.generation.mode == MODE_TWO:
            return self._two_layer_generator(planned)
        return self._single_generator(planned, provider)

    def _execute_all(
        self,
        plan: Plan,
        before: Callable[[PlannedOutput], "str | None"] | None = None,
    ) -> tuple[int, int]:
        """Выполнить план.

        ``before(planned)`` вызывается ДО генерации и возвращает сообщение
        guard-а (или ``None``) — так проверка «не воспроизводим отклонённое»
        происходит раньше переноса файла, как в контрактном алгоритме.
        """

        succeeded = 0
        failed = 0

        def handle(planned: PlannedOutput, provider: Callable[[], Any] | None) -> None:
            nonlocal succeeded, failed
            violation = before(planned) if before is not None else None
            ok = self._process_output(
                planned,
                self._generator_for(planned, provider),
                self._intermediates(planned),
                guard_violation=violation,
            )
            succeeded += int(ok)
            failed += int(not ok)

        if not plan.outputs:
            # Делать нечего — бэкенды не создаются вовсе. Это важно на машинах
            # без CUDA/MPS, где конструирование пайплайна само по себе падает:
            # повторный «уже всё готово» прогон обязан быть честным no-op.
            return succeeded, failed

        if self.job.generation.mode == MODE_TWO:
            for planned in plan.outputs:
                handle(planned, None)
            return succeeded, failed

        # single_layer: один generator на весь прогон (кэш VRAM), но создаётся он
        # лениво — прогон, целиком остановленный guard-ом, тоже не грузит модель.
        with ExitStack() as stack:
            cache: dict[str, Any] = {}

            def provider() -> Any:
                if "generator" not in cache:
                    cache["generator"] = stack.enter_context(
                        self.deps.backends.make_generator(self.model_id)
                    )
                return cache["generator"]

            for planned in plan.outputs:
                handle(planned, provider)
        return succeeded, failed

    # ----------------------------------------------------------------- вывод
    def _print_header(self, plan: Plan) -> None:
        self._print(f"datasetgen {self.command}: {self.job.source_path}")
        self._print(f"  model_id:   {self.model_id}")
        self._print(f"  output_dir: {self.root}")
        self._print(
            f"  task: {self.job.task}  mode: {self.job.generation.mode}  job_seed: {self.job.seed}"
        )
        self._print(
            "  classes: " + ", ".join(f"{spec.name}={spec.count}" for spec in self.job.classes)
        )
        self._print(
            f"  plan: {len(plan.outputs)} output(s) to process, {len(plan.complete)} already complete"
        )

    def _print_dry_run(self, plan: Plan) -> None:
        total = len(plan.outputs)
        for position, planned in enumerate(plan.outputs, start=1):
            self._print(
                f"[{position}/{total}] {planned.class_name}/{planned.index}"
                f" attempt={planned.attempt} seed={planned.seed}"
                f" -> {planned.class_name}/{planned.filename}"
            )
            self._print(f"    prompt: {planned.prompt}")
            if self.job.generation.mode == MODE_TWO:
                self._print(f"    background prompt: {background_prompt(self.job, planned.material)}")
        for planned in plan.complete:
            self._print(f"[complete] {planned.class_name}/{planned.index} attempt={planned.attempt}")
        self._print(
            "dry-run: nothing was written "
            "(no directories, no files, no manifest.jsonl, no backends were used)"
        )

    def _print_summary(self, plan: Plan, succeeded: int, failed: int) -> None:
        self._print(
            f"summary: planned={len(plan.outputs)} succeeded={succeeded} failed={failed}"
            f" already_complete={len(plan.complete)} rejected_moved={self.rejected_moved}"
        )
        for message in self.failures[:10]:
            self._print(f"  failure: {message}")
        if len(self.failures) > 10:
            self._print(f"  ... and {len(self.failures) - 10} more failure(s)")

    def _start_writing(self, plan: Plan, removed: Sequence[tuple[str, int]] | None = None) -> None:
        self._preflight_overwrite(plan)
        self._make_directories()
        self.manifest.repair_truncated_tail()  # R9 — до первой записи
        self.started_at = self._timestamp()
        self.run_id = self._make_run_id(self.started_at)
        self._write_run_record(removed=removed)
        self._disk_gap_report()

    def _finish(self, plan: Plan, succeeded: int, failed: int, *, skipped_complete: int) -> RunResult:
        self._print_summary(plan, succeeded, failed)
        self._write_description(succeeded=succeeded, failed=failed)
        return RunResult(
            command=self.command,
            planned=len(plan.outputs),
            succeeded=succeeded,
            failed=failed,
            skipped_complete=skipped_complete,
            rejected_moved=self.rejected_moved,
            written=True,
            exit_code=EXIT_GENERATION_FAILED if failed else EXIT_OK,
        )

    def _dry_result(self, plan: Plan, *, skipped_complete: int) -> RunResult:
        self._print_dry_run(plan)
        return RunResult(
            command=self.command,
            planned=len(plan.outputs),
            succeeded=0,
            failed=0,
            skipped_complete=skipped_complete,
            rejected_moved=0,
            written=False,
            exit_code=EXIT_OK,
        )

    # -------------------------------------------------------------- прогон run
    def run(self) -> RunResult:
        plan = self._prepare()
        self._print_header(plan)
        if self.dry_run:
            return self._dry_result(plan, skipped_complete=len(plan.complete))
        self._start_writing(plan)
        succeeded, failed = self._execute_all(plan)
        return self._finish(plan, succeeded, failed, skipped_complete=len(plan.complete))

    # ------------------------------------------------------- прогон regenerate
    def regenerate(self, selection: Sequence[tuple[str, int]]) -> RunResult:
        plan = self._prepare(selection=selection)
        self._print_header(plan)
        if self.dry_run:
            return self._dry_result(plan, skipped_complete=0)
        self._start_writing(plan, removed=selection)

        def before(planned: PlannedOutput) -> str | None:
            violation = self._guard_message(planned)
            if violation is not None:
                # Guard срабатывает ДО переноса: файл остаётся на месте.
                return violation
            self._reject_existing(planned, self.state.attempts(planned.key))
            return None

        succeeded, failed = self._execute_all(plan, before=before)
        return self._finish(plan, succeeded, failed, skipped_complete=0)

    # ------------------------------------------------------- отклонение (R7)
    def _reject_existing(self, planned: PlannedOutput, old_attempt: int) -> None:
        final = layout.final_image_path(self.root, planned.class_name, planned.index)
        previous = self.state.last_record(planned.key) or {}

        if previous.get("status") == STATUS_FAILED:
            # Попытка не дала готового кадра, отклонять нечего: переход
            # failed -> rejected в графе статусов не предусмотрен. Остаточный
            # файл манифестом уже описан (R5), его перезапишет новая попытка.
            if final.exists():
                self.warn(
                    f"replacing the leftover of a failed attempt for "
                    f"{planned.class_name}/{planned.index}: {final}"
                )
            return

        moved_to: str | None = None
        if final.exists():
            target = layout.rejected_path(self.root, planned.class_name, planned.index, old_attempt)
            if target.exists():
                raise UnsafePathError(f"rejected target already exists: {target}")
            target.parent.mkdir(parents=True, exist_ok=True)
            final.replace(target)
            moved_to = layout.relative_posix(self.root, target)
            self.rejected_moved += 1
        else:
            self.warn(
                f"nothing to reject for {planned.class_name}/{planned.index}: {final} does not exist"
            )

        if old_attempt > 0 and not self.state.is_rejected(planned.key):
            self.manifest.append(
                self._image_record(
                    planned,
                    STATUS_REJECTED,
                    timestamp=self._timestamp(),
                    attempt=old_attempt,
                    seed=previous.get("seed"),
                    prompt=previous.get("prompt"),
                    negative_prompt=previous.get("negative_prompt"),
                    rejected_file=moved_to,
                    reason="cli --remove",
                )
            )
        self.state = self.manifest.state()

    # ---------------------------------------------------------------- отчёты
    def _write_description(self, *, succeeded: int, failed: int) -> None:
        if not self.job.description.enabled:
            return
        write_reports(
            job=self.job,
            model_id=self.model_id,
            root=self.root,
            state=self.manifest.state(),
            succeeded=succeeded,
            failed=failed,
            rejected_moved=self.rejected_moved,
            errors=self.failures,
            warn=self.warn,
        )


def run_job(
    job: JobConfig,
    model_id: str,
    *,
    output_dir: Path | None = None,
    dry_run: bool,
    deps: "Dependencies",
    out: Any = None,
    warn: Callable[[str], None] | None = None,
    error: Callable[[str], None] | None = None,
) -> RunResult:
    """Сгенерировать все недостающие выходы (resume)."""

    execution = _Execution(
        job,
        model_id,
        output_dir,
        dry_run,
        deps,
        "run",
        out=out if out is not None else _NullWriter(),
        warn=warn if warn is not None else _noop,
        error=error if error is not None else _noop,
    )
    return execution.run()


def regenerate(
    job: JobConfig,
    model_id: str,
    selection: str | Sequence[tuple[str, int]],
    *,
    output_dir: Path | None = None,
    dry_run: bool,
    deps: "Dependencies",
    out: Any = None,
    warn: Callable[[str], None] | None = None,
    error: Callable[[str], None] | None = None,
) -> RunResult:
    """Отклонить выбранные индексы и перегенерировать их (attempt+1)."""

    if isinstance(selection, str):
        from .selectors import parse_remove  # noqa: PLC0415 - ленивый импорт

        keys = parse_remove(selection, job.class_names(), job.class_counts(), job.task)
    else:
        keys = tuple(selection)
    execution = _Execution(
        job,
        model_id,
        output_dir,
        dry_run,
        deps,
        "regenerate",
        out=out if out is not None else _NullWriter(),
        warn=warn if warn is not None else _noop,
        error=error if error is not None else _noop,
    )
    return execution.regenerate(keys)


def _noop(message: str) -> None:  # pragma: no cover - заглушка вывода
    return None
